### ISSUE TITLE
Can we limit secretRef scope

### ISSUE THREAD

**Issue by duxinxiao** [jniebuhr/aws-pca-issuer#26]
it seems thats, AWSPCAIssuer can use any secrets in any namespaces. it may cause security problems.

**Comment by jniebuhr** [comment]
Hi @duxinxiao, the RBAC that’s included in the helm chart can be switched off and you can supply your own rules. You can check the default values for further information

**Comment by duxinxiao** [comment]
Thanks for your time, just forgot this value in chart, will close this issue
