### ISSUE TITLE
Consider bumping to v2 of the go SDK

### ISSUE THREAD

**Issue by liamawhite** [jniebuhr/aws-pca-issuer#4]
In private EKS clusters, VPC endpoints are typically created for regional endpoints. 

The AWS sdk in v1 defaults to using the global sts endpoint so the issuer doesn't work without setting an additional env var: `AWS_STS_REGIONAL_ENDPOINTS: 'regional'`. If using the v2 sdk it uses regional by default as documented [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list).

**Comment by jniebuhr** [comment]
Thanks for the suggestion, I'll take a look at it.

**Comment by dtjm** [comment]
I was troubleshooting some issues with the operator and as a step to try to figure out the issue, I converted it to use aws-go-sdk-v2.  If you are interested I can push up my changes.

**Comment by jniebuhr** [comment]
@dtjm Yes, that sounds great. It would be nice if you can submit a PR
